# Generated by Django 4.1.3 on 2022-12-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_postviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
    ]
